import { useState } from 'react'
import { CheckCircle2, MapPin, Save, Sun, Wrench } from 'lucide-react'
import FormField, { fieldClassName } from '../../components/FormField.jsx'

const empty={codigo:'',nomeUsina:'',cliente:'',documento:'',status:'Ativa',dataCadastro:'',dataOperacao:'',cep:'',endereco:'',numero:'',complemento:'',bairro:'',cidade:'',uf:'MG',latitude:'',longitude:'',potenciaKwp:'',unidadePotencia:'kWp',quantidadeModulos:'',potenciaModulo:'',fabricanteModulos:'',modeloModulos:'',quantidadeInversores:'',fabricanteInversores:'',modeloInversores:'',strings:'',estrutura:'',tipoInstalacao:'',tensao:'',observacoes:''}

export default function UsinaCadastroPage(){
 const [v,setV]=useState(empty),[errors,setErrors]=useState({}),[toast,setToast]=useState('')
 function change(e){const{name,value}=e.target;setV(x=>({...x,[name]:value}));if(errors[name])setErrors(x=>({...x,[name]:undefined}))}
 function submit(e){e.preventDefault();const er={};if(!v.codigo.trim())er.codigo='Informe o código.';if(!v.nomeUsina.trim())er.nomeUsina='Informe o nome da usina.';if(!v.cliente.trim())er.cliente='Informe o cliente.';if(!v.endereco.trim())er.endereco='Informe o endereço.';if(!v.cidade.trim())er.cidade='Informe a cidade.';if(!v.potenciaKwp||Number(v.potenciaKwp)<=0)er.potenciaKwp='Informe a potência instalada.';setErrors(er);if(Object.keys(er).length)return;setToast('Usina cadastrada com sucesso no modo demonstração.');setV(empty);setTimeout(()=>setToast(''),4000)}
 const field=(name,label,type='text',extra={})=><FormField id={name} label={label} error={errors[name]}><input id={name} name={name} type={type} value={v[name]} onChange={change} className={fieldClassName(errors[name])} {...extra}/></FormField>
 return <section className="relative space-y-6">{toast&&<div className="fixed right-6 top-6 z-50 flex items-start gap-3 rounded-2xl border border-solar-green/30 bg-white px-4 py-3 shadow-card"><CheckCircle2 className="mt-0.5 text-solar-green"/><div><p className="text-sm font-semibold text-navy-900">Cadastro concluído</p><p className="text-sm text-slate-600">{toast}</p></div></div>}<header><p className="text-xs font-semibold uppercase tracking-[0.14em] text-solar-green">Gestão de Usinas</p><h2 className="page-title">Cadastro de Usina</h2><p className="page-subtitle">Cadastro técnico e operacional. Campos não essenciais permanecem opcionais para não bloquear o atendimento.</p></header>
 <form onSubmit={submit} noValidate className="space-y-5">
  <Section icon={Sun} title="Identificação" desc="Vínculo operacional entre cliente e unidade fotovoltaica."><div className="grid gap-4 md:grid-cols-3">{field('codigo','Código','text',{placeholder:'U-001'})}{field('nomeUsina','Nome da usina','text',{placeholder:'Usina Solar ABC'})}{field('cliente','Cliente','text',{placeholder:'Empresa Solar ABC'})}{field('documento','Documento do cliente')}{<FormField id="status" label="Status"><select id="status" name="status" value={v.status} onChange={change} className={fieldClassName()}><option>Ativa</option><option>Em instalação</option><option>Inativa</option></select></FormField>}{field('dataCadastro','Data de cadastro','date')}{field('dataOperacao','Início da operação','date')}</div></Section>
  <Section icon={MapPin} title="Localização" desc="Endereço e coordenadas para uso operacional futuro."><div className="grid gap-4 md:grid-cols-4">{field('cep','CEP')}{field('endereco','Endereço')}{field('numero','Número')}{field('complemento','Complemento')}{field('bairro','Bairro')}{field('cidade','Cidade')}{<FormField id="uf" label="UF"><select id="uf" name="uf" value={v.uf} onChange={change} className={fieldClassName()}>{['MG','SP','GO','RJ','PR','SC','RS','BA','ES','DF'].map(x=><option key={x}>{x}</option>)}</select></FormField>}{field('latitude','Latitude')}{field('longitude','Longitude')}</div></Section>
  <Section icon={Sun} title="Informações técnicas" desc="Dados de dimensionamento e equipamentos, com preenchimento progressivo."><div className="grid gap-4 md:grid-cols-3">{field('potenciaKwp','Potência instalada','number',{min:'0',step:'0.1',placeholder:'500'})}{field('unidadePotencia','Unidade','text',{placeholder:'kWp'})}{field('quantidadeModulos','Quantidade de módulos','number',{min:'0'})}{field('potenciaModulo','Potência dos módulos','number',{min:'0',step:'0.1'})}{field('fabricanteModulos','Fabricante dos módulos')}{field('modeloModulos','Modelo dos módulos')}{field('quantidadeInversores','Quantidade de inversores','number',{min:'0'})}{field('fabricanteInversores','Fabricante dos inversores')}{field('modeloInversores','Modelo dos inversores')}{field('strings','Quantidade de strings','number',{min:'0'})}{field('estrutura','Estrutura de fixação')}{field('tipoInstalacao','Tipo de instalação')}{field('tensao','Tensão')}</div><FormField id="observacoes" label="Informações relevantes"><textarea id="observacoes" name="observacoes" value={v.observacoes} onChange={change} className={fieldClassName()} rows="3"/></FormField></Section>
  <div className="flex justify-end"><button className="btn-primary"><Save size={16}/> Salvar usina</button></div>
 </form></section>
}
function Section({icon:Icon,title,desc,children}){return <section className="surface-card overflow-hidden"><header className="flex items-start gap-3 border-b border-slate-100 bg-slate-50/70 px-5 py-4"><span className="rounded-xl bg-navy-900 p-2 text-solar-yellow"><Icon size={16}/></span><div><h3 className="text-sm font-semibold text-navy-900">{title}</h3><p className="text-xs text-slate-500">{desc}</p></div></header><div className="space-y-4 p-5">{children}</div></section>}
