import { useMemo, useState } from 'react'
import { FileDown, Printer, BarChart3 } from 'lucide-react'
import { formatCurrency } from '../../components/ui.jsx'
const reports={
 'vendas': {title:'Relatório comercial',subtitle:'Propostas, oportunidades e contratos em acompanhamento.',columns:['Indicador','Quantidade','Valor'],rows:[['Oportunidades',27,formatCurrency(1840000)],['Propostas abertas',14,formatCurrency(1351400)],['Contratos ativos',38,formatCurrency(0)]]},
 'operacao': {title:'Relatório de manutenção',subtitle:'Agenda de serviços e contratos de manutenção.',columns:['Cliente','Serviço','Data','Status'],rows:[['Fazenda Santa Luz','Limpeza de módulos','04/10/2026','Agendada'],['Mercado Bom Preço','Manutenção preventiva','06/10/2026','Agendada'],['Residencial Aurora','Limpeza de módulos','07/10/2026','Confirmada'],['Clínica Vida Plena','Inspeção elétrica','09/10/2026','Pendente']]},
 'financeiro': {title:'Relatório financeiro',subtitle:'Resumo demonstrativo para validação do layout.',columns:['Indicador','Valor'],rows:[['Contas a receber',formatCurrency(284500)],['Contas a pagar',formatCurrency(173200)],['Saldo operacional',formatCurrency(111300)]]},
}
export default function RelatoriosPage(){const [type,setType]=useState('vendas');const r=useMemo(()=>reports[type],[type]);return <section className="space-y-5"><header className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-solar-green">Gestão</p><h2 className="page-title">Relatórios</h2><p className="page-subtitle">Geração de relatórios demonstrativos para validação e apresentação.</p></div><div className="flex gap-2"><button className="btn-secondary" onClick={()=>window.print()}><Printer size={16}/> Imprimir / PDF</button><button className="btn-primary" onClick={()=>window.print()}><FileDown size={16}/> Gerar relatório</button></div></header><div className="grid gap-4 md:grid-cols-3">{Object.entries(reports).map(([k,v])=><button key={k} onClick={()=>setType(k)} className={`surface-card p-4 text-left ${type===k?'ring-2 ring-navy-800/10':''}`}><BarChart3 size={18} className="text-navy-800"/><p className="mt-3 text-sm font-semibold text-navy-900">{v.title}</p><p className="mt-1 text-xs text-slate-500">{v.subtitle}</p></button>)}</div><article className="surface-card overflow-hidden"><div className="border-b border-slate-200 p-6"><p className="text-xs uppercase tracking-wider text-slate-400">Kaelo ERP · Relatório demonstrativo</p><h3 className="mt-1 text-xl font-bold text-navy-900">{r.title}</h3><p className="mt-1 text-sm text-slate-500">{r.subtitle}</p><p className="mt-3 text-xs text-slate-400">Período: demonstração · Empresa: organização selecionada</p></div><div className="overflow-x-auto"><table className="data-table"><thead><tr>{r.columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{r.rows.map((row,i)=><tr key={i}>{row.map((cell,j)=><td key={j} className={j===0?'font-medium':''}>{cell}</td>)}</tr>)}</tbody></table></div><div className="border-t border-slate-200 p-4 text-xs text-slate-400">Dados demonstrativos para validação de layout. A fonte será substituída pelos dados reais na etapa de persistência.</div></article></section>}
