import { Link } from 'react-router-dom'
import { ArrowRight, Banknote, BatteryCharging, CreditCard, KeyRound, Settings2, SunMedium } from 'lucide-react'
const sections=[
 {to:'/configuracoes/acessos',title:'Configurações de Acesso',text:'Usuários, grupos e perfis. Define o que cada pessoa pode visualizar e executar.',icon:KeyRound},
 {to:'/configuracoes/ufv/ongrid',title:'Gestão UFV · Parâmetros On-grid',text:'Eficiência, perdas e parâmetros técnicos por modelo de inversor e cenário.',icon:SunMedium},
 {to:'/configuracoes/ufv/hibrido',title:'Gestão UFV · Parâmetros Híbrido',text:'Baterias, DoD, eficiência, degradação, potência, autonomia e compatibilidade.',icon:BatteryCharging},
 {to:'/configuracoes/financeiro/receber',title:'Financeiro · Contas a Receber',text:'Regras de cobrança, juros, multa, antecipação e meios de pagamento.',icon:Banknote},
 {to:'/configuracoes/financeiro/bancaria',title:'Financeiro · Configuração Bancária',text:'Contas, convênios, remessa, retorno e DDA conforme disponibilidade do banco.',icon:CreditCard},
]
export default function ConfiguracoesPage(){return <section className="space-y-6"><header><p className="text-xs font-semibold uppercase tracking-[0.14em] text-solar-green">Administração</p><h2 className="page-title">Configurações</h2><p className="page-subtitle">Cada módulo possui aqui suas configurações específicas, sem duplicar cadastros ou tabelas operacionais.</p></header><div className="grid gap-4 md:grid-cols-2">{sections.map(({to,title,text,icon:Icon})=><Link key={title} to={to} className="surface-card group p-5 transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-start justify-between"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-navy-900/5 text-navy-800"><Icon size={19}/></div><ArrowRight size={18} className="text-slate-400 group-hover:translate-x-0.5"/></div><h3 className="mt-4 font-semibold text-navy-900">{title}</h3><p className="mt-1 text-sm leading-6 text-slate-500">{text}</p></Link>)}</div><div className="surface-card flex items-start gap-3 p-5"><Settings2 size={19} className="mt-0.5 text-solar-green"/><div><p className="font-semibold text-navy-900">Princípio de configuração</p><p className="mt-1 text-sm leading-6 text-slate-500">Configuração não cria um novo cadastro. Ela parametriza o comportamento da mesma base de dados, respeitando licença, empresa, grupo e perfil.</p></div></div></section>}
