import { CalendarDays, CheckCircle2, Clock3, Plus, Search } from 'lucide-react'
import { useMemo, useState } from 'react'
import { StatusBadge } from '../../components/ui.jsx'

const initial = [
 {id:'ATV-001',usina:'Usina SL-12 kWp',cliente:'Fazenda Santa Luz',servico:'Limpeza dos módulos',grupo:'Limpeza',familia:'Módulos',periodicidade:'Trimestral',proxima:'2026-10-04',status:'Agendada',tecnico:'Ana Souza'},
 {id:'ATV-002',usina:'Cobertura 45 kWp',cliente:'Mercado Bom Preço',servico:'Inspeção preventiva',grupo:'Manutenção',familia:'Preventiva',periodicidade:'Semestral',proxima:'2026-10-06',status:'Planejada',tecnico:'Carlos Lima'},
 {id:'ATV-003',usina:'Telhado 8,2 kWp',cliente:'Residencial Aurora',servico:'Limpeza dos módulos',grupo:'Limpeza',familia:'Módulos',periodicidade:'Semestral',proxima:'2026-10-07',status:'Confirmada',tecnico:'Pedro Alves'},
 {id:'ATV-004',usina:'Solo 180 kWp',cliente:'Indústria Vale Verde',servico:'Relatório mensal de desempenho',grupo:'Monitoramento',familia:'Desempenho',periodicidade:'Mensal',proxima:'2026-10-10',status:'Planejada',tecnico:'Rafael Costa'},
]
const next={Planejada:'Agendada',Agendada:'Confirmada',Confirmada:'Em execução','Em execução':'Concluída'}
export default function PlanejamentoPage(){
 const [items,setItems]=useState(initial),[q,setQ]=useState(''),[modal,setModal]=useState(false)
 const rows=useMemo(()=>items.filter(i=>Object.values(i).some(v=>String(v).toLowerCase().includes(q.toLowerCase()))),[items,q])
 function advance(item){if(!next[item.status])return;setItems(x=>x.map(i=>i.id===item.id?{...i,status:next[i.status]}:i))}
 return <section className="space-y-5">
  <header className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-solar-green">Gestão de Usinas · O&M</p><h2 className="page-title">Planejamento O&M</h2><p className="page-subtitle">Atividades recorrentes e agenda operacional: planejado → agendado → executado → comprovado.</p></div><div className="flex gap-2"><div className="relative"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input className="input pl-9" placeholder="Pesquisar..." value={q} onChange={e=>setQ(e.target.value)}/></div><button className="btn-primary" onClick={()=>setModal(true)}><Plus size={16}/> Nova atividade</button></div></header>
  <div className="grid gap-4 md:grid-cols-4">{[['Hoje',rows.filter(i=>i.proxima==='2026-10-04').length],['Planejadas',rows.filter(i=>i.status==='Planejada').length],['Agendadas',rows.filter(i=>i.status==='Agendada').length],['Concluídas',rows.filter(i=>i.status==='Concluída').length]].map(([l,v])=><div key={l} className="surface-card p-4"><p className="text-xs text-slate-500">{l}</p><p className="mt-1 text-xl font-bold text-navy-900">{v}</p></div>)}</div>
  <div className="surface-card overflow-hidden"><div className="overflow-x-auto"><table className="data-table"><thead><tr><th>Atividade</th><th>Usina</th><th>Grupo/Família</th><th>Periodicidade</th><th>Próxima</th><th>Técnico</th><th>Status</th><th>Ação</th></tr></thead><tbody>{rows.map(i=><tr key={i.id}><td className="font-medium">{i.servico}</td><td>{i.usina}</td><td>{i.grupo} / {i.familia}</td><td>{i.periodicidade}</td><td>{i.proxima}</td><td>{i.tecnico}</td><td><StatusBadge tone={i.status==='Concluída'?'green':i.status==='Planejada'?'yellow':'navy'}>{i.status}</StatusBadge></td><td>{next[i.status]?<button className="text-xs font-semibold text-navy-800 hover:underline" onClick={()=>advance(i)}>Avançar</button>:<CheckCircle2 size={16} className="text-solar-green"/>}</td></tr>)}</tbody></table></div></div>
  {modal&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4"><form onSubmit={e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget));setItems(x=>[{id:'ATV-'+String(x.length+1).padStart(3,'0'),...v,status:'Planejada'},...x]);setModal(false)}} className="w-full max-w-2xl rounded-2xl bg-white p-6 shadow-xl"><div className="flex items-center gap-3"><CalendarDays className="text-solar-green"/><div><h3 className="text-lg font-semibold text-navy-900">Nova atividade recorrente</h3><p className="text-xs text-slate-500">Cadastro demonstrativo de uma atividade operacional.</p></div></div><div className="mt-5 grid gap-4 md:grid-cols-2"><label className="field"><span>Usina</span><input name="usina" className="input" required/></label><label className="field"><span>Cliente</span><input name="cliente" className="input" required/></label><label className="field md:col-span-2"><span>Serviço</span><input name="servico" className="input" placeholder="Ex.: Limpeza dos módulos" required/></label><label className="field"><span>Periodicidade</span><select name="periodicidade" className="input"><option>Mensal</option><option>Trimestral</option><option>Semestral</option><option>Anual</option></select></label><label className="field"><span>Próxima execução</span><input name="proxima" type="date" className="input" required/></label><label className="field"><span>Técnico/equipe</span><input name="tecnico" className="input" required/></label></div><div className="mt-6 flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={()=>setModal(false)}>Cancelar</button><button className="btn-primary">Criar atividade</button></div></form></div>}
 </section>
}