import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { ArrowRight, CalendarDays, FileText, Plus, ReceiptText, Search, UsersRound, MoveRight } from 'lucide-react'
import { formatCurrency, StatusBadge } from '../../components/ui.jsx'

const initial = [
  { id: 'OP-001', cliente: 'Clínica Vida Plena', contato: 'Mariana Alves', valor: 148900, etapa: 'Proposta enviada', proximo: '2026-10-05', atividade: 'Retorno da proposta' },
  { id: 'OP-002', cliente: 'Escola Horizonte', contato: 'Rafael Costa', valor: 312000, etapa: 'Prospecção', proximo: '2026-10-04', atividade: 'Reunião comercial' },
  { id: 'OP-003', cliente: 'Condomínio Solar Park', contato: 'Paulo Mendes', valor: 890500, etapa: 'Negociação', proximo: '2026-10-06', atividade: 'Revisar condições' },
  { id: 'OP-004', cliente: 'Fazenda Santa Luz', contato: 'Luciana Reis', valor: 76000, etapa: 'Ganho', proximo: '2026-10-08', atividade: 'Agendar implantação' },
]
const stages = ['Prospecção','Proposta enviada','Negociação','Ganho']
const blocks = [
 { to:'/crm', title:'Leads', text:'Entrada, acompanhamento e conversão de oportunidades.', icon:UsersRound },
 { to:'/propostas', title:'Propostas', text:'Orçamentos e propostas comerciais vinculados ao cliente.', icon:FileText },
 { to:'/comercial/faturamento', title:'Faturamento', text:'Preparação do faturamento a partir do processo comercial.', icon:ReceiptText },
 { to:'/contratos', title:'Contratos', text:'Vigência, escopo, valores e continuidade da venda.', icon:FileText },
]

export default function CRMPage() {
 const [items,setItems]=useState(initial),[q,setQ]=useState(''),[modal,setModal]=useState(false)
 const rows=useMemo(()=>items.filter(i=>Object.values(i).some(v=>String(v).toLowerCase().includes(q.toLowerCase()))),[items,q])
 function save(e){e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget));setItems(x=>[...x,{id:`OP-${String(x.length+1).padStart(3,'0')}`,...v,valor:Number(v.valor||0)}]);setModal(false)}
 function advance(id){setItems(x=>x.map(i=>{if(i.id!==id)return i;const n=stages.indexOf(i.etapa);return {...i,etapa:stages[Math.min(n+1,stages.length-1)]}}))}
 return <section className="space-y-6">
  <header className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-solar-green">Módulo</p><h2 className="page-title">CRM</h2><p className="page-subtitle">Leads, propostas, faturamento e contratos em um único fluxo comercial.</p></div><div className="flex gap-2"><div className="relative"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input className="input pl-9" placeholder="Pesquisar oportunidade..." value={q} onChange={e=>setQ(e.target.value)}/></div><button className="btn-primary" onClick={()=>setModal(true)}><Plus size={16}/> Novo lead</button></div></header>
  <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{blocks.map(({to,title,text,icon:Icon})=><Link key={title} to={to} className="surface-card group p-5 transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-start justify-between"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-navy-900/5 text-navy-800"><Icon size={18}/></div><ArrowRight size={17} className="text-slate-400 group-hover:translate-x-0.5"/></div><h3 className="mt-4 font-semibold text-navy-900">{title}</h3><p className="mt-1 text-sm leading-6 text-slate-500">{text}</p></Link>)}</div>
  <div className="surface-card p-4"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Funil comercial</p><p className="mt-1 text-sm text-slate-600">O lead evolui sem duplicar o cadastro do parceiro. Ao ganhar, o processo pode seguir para proposta, contrato e execução.</p></div><div className="rounded-xl bg-slate-50 px-4 py-2 text-xs text-slate-500">Base compartilhada: Parceiros</div></div></div>
  <div className="grid gap-4 md:grid-cols-4">{stages.map(s=><div key={s} className="surface-card p-4"><p className="text-xs text-slate-500">{s}</p><p className="mt-1 text-xl font-bold text-navy-900">{rows.filter(i=>i.etapa===s).length}</p><p className="mt-1 text-xs text-slate-400">{formatCurrency(rows.filter(i=>i.etapa===s).reduce((a,i)=>a+i.valor,0))}</p></div>)}</div>
  <div className="grid gap-4 xl:grid-cols-4">{stages.map(stage=><div key={stage} className="rounded-2xl bg-slate-100/70 p-3 min-h-52"><div className="mb-3 flex items-center justify-between"><span className="text-sm font-semibold text-navy-900">{stage}</span><span className="text-xs text-slate-400">{rows.filter(i=>i.etapa===stage).length}</span></div><div className="space-y-3">{rows.filter(i=>i.etapa===stage).map(i=><article key={i.id} className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex justify-between gap-2"><span className="text-[10px] font-semibold text-slate-400">{i.id}</span><StatusBadge tone={stage==='Ganho'?'green':stage==='Negociação'?'yellow':'slate'}>{stage}</StatusBadge></div><h3 className="mt-2 text-sm font-semibold text-navy-900">{i.cliente}</h3><p className="text-xs text-slate-500">{i.contato}</p><p className="mt-3 text-sm font-semibold text-navy-900">{formatCurrency(i.valor)}</p><div className="mt-3 flex items-center gap-2 text-xs text-slate-500"><CalendarDays size={13}/>{i.proximo} · {i.atividade}</div>{stage!=='Ganho'&&<button onClick={()=>advance(i.id)} className="mt-3 inline-flex items-center gap-1 text-xs font-semibold text-navy-800 hover:underline">Avançar etapa <MoveRight size={13}/></button>}</article>)}</div></div>)}</div>
  {modal&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4"><form onSubmit={save} className="w-full max-w-xl rounded-2xl bg-white p-6 shadow-xl"><h3 className="text-lg font-semibold text-navy-900">Novo lead</h3><div className="mt-5 grid gap-4 md:grid-cols-2"><label className="field md:col-span-2"><span>Cliente / empresa</span><input name="cliente" className="input" required/></label><label className="field"><span>Contato</span><input name="contato" className="input" required/></label><label className="field"><span>Valor estimado</span><input name="valor" type="number" className="input" required/></label><label className="field"><span>Etapa</span><select name="etapa" className="input">{stages.map(s=><option key={s}>{s}</option>)}</select></label><label className="field"><span>Próximo contato</span><input name="proximo" type="date" className="input" required/></label><label className="field md:col-span-2"><span>Atividade</span><input name="atividade" className="input" required/></label></div><div className="mt-6 flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={()=>setModal(false)}>Cancelar</button><button className="btn-primary">Salvar localmente</button></div></form></div>}
 </section>
}